const QUESTIONS = [
  "Pizza or Burgers?",
  "Roses or Love letters?",
  "Coffee or Tea?",
  "Slow dancing in the kitchen or Making out in the rain?",
  "Cake or Ice Cream?",
  "Kisses on the lips or Kisses on the neck?",
  "Beach vacation or Mountain getaway?",
  "Candlelit dinner or Picnic under the stars?",
  "Marvel or DC?",
  "Slow and teasing or Fast and passionate?",
  "Afrobeats or Hip-Hop?",
  "Lights on or Lights off?",
  "Early bird or Night owl?",
  "Top or Bottom?",
  "Dogs or Cats?",
  "Dirty talk or Moaning only?",
  "Lagos or London?",
  "Massage with oil or Shower together?",
  "Romantic comedy or Action movie?",
  "Morning intimacy or Nighttime passion?",
  "Chocolate or Vanilla?",
  "Gentle bites or Soft scratches?",
  "Road trip or Flight?",
  "Eye contact the whole time or Eyes closed in pleasure?",
  "Singing in the car or Dancing in the kitchen?",
  "Teasing for hours or Quick and intense?",
  "Sunrise or Sunset?",
  "Roleplay as strangers or As your favorite characters?",
  "Gym or Home workout?",
  "Blindfold or Handcuffs (light)?",
  "Nigerian Jollof or Fried Rice?",
  "Beach at night or Private pool at midnight?",
  "Holding hands in public or Secret touches under the table?",
  "Public risk (teasing) or Private only?",
  "Netflix or YouTube?",
  "Dominating or Being dominated?",
  "Planner or Spontaneous?",
  "Watching each other or Mutual pleasure?",
  "Concert or Karaoke night?",
  "Food play (chocolate, whipped cream) or Ice cube play?",
  "Messy or Organized?",
  "Lingerie or Nothing at all?",
  "Texting or Calling?",
  "Shower sex or Bathtub together?",
  "Love songs or Party songs?",
  "Romantic movie at home or Dancing at a club?",
  "Introvert or Extrovert?",
  "Cooking naked together or Feeding each other in bed?",
  "Big party or Small gathering?",
  "Stargazing and cuddling or Hot tub under the moon?",
  "Sushi or Shawarma?",
  "Wine tasting or Chocolate tasting (on each other)?",
  "Optimist or Realist?",
  "Flirty texts all day or Surprise spicy photos?",
  "Reading a book or Watching a movie?",
  "Sunset cruise or Midnight drive with music?",
  "Sweet or Salty snacks?",
  "Couple’s spa day or Private yacht date?",
  "Horror movie or Thriller?",
  "Love language: Words of affirmation or Physical touch?",
  "Camping or Luxury hotel?",
  "Quick kiss or Long passionate kiss?",
  "Anime or Cartoon?",
  "Foreplay for 30 minutes or All-night session?",
  "Matching couple outfits or Secret matching tattoos?",
  "Cuddling after or Round two immediately?",
  "Paris or Dubai?",
  "Whisper “I love you” or Moan my name?",
  "Gaming together or Cooking together?",
  "Romantic playlist or Complete silence?",
  "Adventure trip or Relaxing staycation?",
  "Love bites or Hickeys?",
  "Quiet night in or Going out?",
  "Soft music or Rain sounds during intimacy?",
  "Good morning texts or Good night voice notes?",
  "Compliments during or After?",
  "Train ride or Boat cruise?",
  "Slow sensual or Rough and wild?",
  "Series binge or One movie?",
  "Falling asleep in each other’s arms or Waking up to more?",
  "Bollywood or Hollywood?",
  "Love poems or Steamy love notes?",
  "Jealousy play (light) or Pure devotion?",
  "Sweet and innocent or Naughty and bold?",
  "Early movie or Late night show?",
  "Watching the sunset together or Cuddling at sunrise?",
  "Old school music or New age?",
  "Surprise weekend getaway or Fancy hotel staycation?",
  "Comedy or Drama?",
  "Breakfast in bed with kisses or Late-night dessert in bed?",
  "Live music or Playlist?",
  "Kisses or Hugs?",
  "Cold weather or Hot weather?",
  "Romantic fantasy or Wild fantasy?",
  "Solo trip or Couple trip?",
  "Dirty talk or Moaning only? (repeat for emphasis 😏)",
  "Superhero movie or Love story?",
  "Gentle or Passionate?",
  "TikTok or Instagram Reels?",
  "All-night cuddling or All-night passion?",
  "What kind of kiss melts you the most — gentle lip brushes, passionate tongue, neck kisses, or forehead kisses?",
  "Can I kiss your forehead… then your cheeks… then your lips… super slowly?",
  "Can I run my finger slowly across your lips before I finally kiss you?",
  "If I whispered “I’ve been thinking about you all day” in your ear, what would you whisper back?",
  "What sweet nickname would you love me to call you when we’re alone?",
  "Do you love when someone gently plays with your hair or traces your skin?",
  "Can I hold your hand while we walk, fingers intertwined, no matter who sees?",
  "Can I wrap my arms around you and hug you tight in public like you’re mine?",
  "Can I kiss you softly in public… or pull you in for a deep one?",
  "Can I spoon you from behind while we watch a movie, kissing your neck softly?",
  "Can we slow-dance in the dark at 3 a.m.? What song would be perfect?",
  "What’s the most romantic thing anyone has ever done for you?",
  "If I stared into your eyes for a full minute and said nothing, what would you feel?",
  "What does a perfect date night look like for you — romantic or wild?",
  "Can we take a long, warm bath together, candles and all?",
  "Can we share one plate of food, feeding each other slowly?",
  "Can we eat dessert with one spoon, stealing kisses between bites?",
  "Can we spend an entire night just talking, touching, and making love?",
  "Right now, on a scale of 1–10, how much do you want me to kiss you?",
  "What’s one thing about me that already turns you on or makes your heart race?",
  "What’s your biggest turn-on that’s not even sexual — something emotional or sweet?",
  "If I told you I want to be your safe place forever, how would that make you feel?",
  "How much do you trust me right now (1–10)? What would make it a 10?",
  "What’s one small daily thing I could do that would make you feel loved?",
  "What’s one thing you need in a relationship to feel truly safe and loved?",
  "Do you believe in soulmates… or do you think love is built over time?",
  "Do you ever picture us building a life together long-term?",
  "If I said “you’re my favorite person” right now, would you believe me?",
  "Can we make a pact — no matter what, we always come back to each other?",
  "What’s one promise you’d want from me if we got serious?",
  "If tonight was our last night together forever… how would you want to spend it?",
  "Are you horny right now… be honest",
  "What do you do when you get horny late at night and no one’s around?",
  "On a scale of sweet to filthy, how naughty are you really? 😈",
  "How do you let your partner know you’re craving sex right now?",
  "If you’re horny, what’s the best way for me to notice and take care of it?",
  "Can I sleep naked with you, bodies pressed together all night?",
  "What sexy song or playlist would you want playing while we’re tangled up?",
  "Do you want to ride me… or should I give you the ride of your life? 😏",
  "One intense round or keep going until we can’t anymore?",
  "Which part of my body are you most curious to see / touch right now?",
  "What’s running through your mind about me at this exact moment?",
  "What’s your body count?",
  "What sex style/position makes you lose control the fastest?",
  "Can you give mind-blowing head… and do you love receiving it?",
  "Favorite place to be licked or to lick on your partner?",
  "What’s your bra size (or chest size)?",
  "Tell me one freaky fantasy you’ve never told anyone",
  "What’s the hottest thing I could whisper to you during foreplay?",
  "Make one wish for us right now — romantic or naughty ✨",
  "To you, what’s the difference between “having sex” and “making love”?",
  "Would you rather fall asleep on late-night calls with me or wrapped in my arms?",
  "If we were long-distance, how would you want me to show I’m still yours?",
  "Do you like being told “I love you” during sex… or saved for special moments?",
  "Can I surprise you with flowers… and then pin you against the wall?",
  "In a relationship, do you prefer lots of public affection or private passion?",
  "If we fought, how would you want me to make it up to you?",
  "Have you ever fallen in love at first sight… or does it take time for you?",
  "If I got down on one knee and proposed (playfully or seriously), what’s your answer?",
  "If the vibe is right, can we fuck tonight?",
  "Can I come home with you tonight… and not leave until morning?",
  "Who’s allowed to touch your body — only someone special, or are you more open?",
  "Can I see it? (your dick / your boobs — your choice tonight)",
  "Send two pics — one cute/romantic of you, one teasing/sexy",
  "Ever had sex?",
  "Age",
  "Are you naughty?",
  "Naughtiest tin u have ever done",
  "Ever exchanged nude?",
  "Buy me a gift",
  "Wil you let me touch you?",
  "Do you love me?",
  "How do you want d dick or pussy to be.",
  "Sex chat with me",
  "Have some mistakenly seeing ur dick or pussy?",
  "What gets u wet",
  "Last time u felt like having sex",
  "Favorite clothes",
  "Ask me anything",
  "Promise to have sex with me",
  "Nickname",
  "Favorite sex position",
  "How long do you want sex to be.",
  "Do you love sex?",
  "Something u will change about yourself",
  "Send me two of your sexiest pics",
  "Tell me how you had ur last time sex in details",
  "How much do you enjoy sex",
  "Tell me things you want from me.",
  "Hard fuck or normal",
  "Send me 2 pics of your dick",
  "Send me 2 pics of your pussy",
  "Hairy dick/pussy or shaved",
  "Send me your dance videos",
  "Will you fuck me?",
  "Ever fucked someone you don't love?",
  "What do you like in a girl",
  "What do you like in a boy",
  "Tell me things you want us to do together",
  "Send me a sex video of yourself",
  "How much do you love sex.",
  "Do you prefer being sucked on your pussy or rather have sex.",
  "Are you horny right now",
  "Do you prefer being sucked on your dick or rather have sex",
  "kiss each other for a whole minute",
  "will you give me a lap dance",
  "what is your favorite body part on a girl?",
  "which do you prefer wet or dry kiss",
  "what is your favorite body part on a boy",
  "have you ever had a sex dream",
  "what on your mind right now",
  "will you come over my place",
  "if we were both inside the room what will you do to me?",
  "What don’t you like about me?",
  "Did you like your first kiss?",
  "Have you ever decided to kiss or make out with a guy just because you were Horny?",
  "Which do you like the most, your boobs or your bum?",
  "What are you wearing right now?",
  "If you ask me to do something naughty what would you prefer I do?",
  "Missionary or doggy-style?",
  "What turns you on the most in a guy?",
  "Is it okay if I kiss you?",
  "How you react if I kissed you immediately I see you next time?",
  "How did you get so beautiful?",
  "Assuming we were stuck together alone in a house for a whole day, what do you think we would do?",
  "What color of panties do you prefer and why?",
  "What is the color of the underpants you are wearing right now?",
  "Are you a boobs or ass man?",
  "Where you do like being touched the most?",
  "Have you ever thought about kissing me?",
  "What if I was naked and laying in your bed?",
  "Do you want to help keep my body warm?",
  "How long do you think a guy should last on bed?",
  "Snap a new pic of urself with the cloth you are wearing right now and send it",
  "Who is your favorite celebrity?",
  "Have you ever had a crush on one of your cousins?",
  "What is your worst habit?",
  "Have you ever dated two girls at the same time?",
  "While you are kissing, what types of other things you prefer to be done simultaneously?",
  "Did you know I can make you shake all over if you let me rub my cap on your clit?",
  "What do my lips taste like?",
  "How do you feel about being fingered?",
  "Where do you like it best? Back or front?",
  "Where is somewhere in my house you would like to have sex in apart fro the bedroom?",
  "Do you want me to talk dirty?",
  "Show me a porn video you’d want us to act out together",
  "Try not to get turned on while I sit on your lap and kiss your neck for 60 seconds.",
  "Would you rather spank someone or be spanked?",
  "Kiss my nipple for 60 seconds.",
  "What’s your biggest sexual fear?",
  "If you had to fuck one animal, what animal would you pick?",
  "Do you love me? How much?",
  "Would you take a shower with me?",
  "How often do you watch something naughty?",
  "How often do you trim down there?",
  "How many people have seen you naked?",
  "What are you wearing?",
  "What’s something you want me to do to you?",
  "Wide or tight p***y",
  "How many kids would you like to have?",
  "Twerk on my lap with only your underwear",
  "wanna suck my pussy?",
  "wanna suck my dick?",
  "Do you prefer rough or slow sex?",
  "Do you like your partner to be silent or loud?",
  "Have you ever cheated in an exam?",
  "When was the first time that you watched porn?",
  "Tell me a Dirty Truth about you that no one else knows?",
  "Do you think I’m Hot?",
  "Who would you most like to make out with?",
  "When is the last time that you touched yourself?",
  "Do you ever walk around in public without any underwear on?",
  "What do you think is the absolutely sexiest part of my body?",
  "If I was tied down to the bed right now, what would you do to me?",
  "Have you ever accidentally grabbed someones butt?",
  "Name one celebrity you would want to make out with",
  "When was the last time you masturbated?",
  "Do you like to listen to music while having sex?",
  "Kiss me passionately?",
  "Tell me how you would make love to me.",
  "Tell me something to get me aroused.",
  "Does naughty talk get you aroused?",
  "Have you ever witnessed people having sex?",
  "which do u prefer, fuck through panties? or fuck without panties?",
  "will u romance me without being asked?",
  "Call me and say “I Love You” along with my name as loud as you can.",
  "Do you prefer texting me or talking to me on the phone?",
  "If you were famous, what would you be famous for?",
  "if I was in the mood for sex, will u give it to me?",
  "What’s one thing you can’t live without?",
  "What’s the last thing you searched on your phone?",
  "Of the people in this room, who do you most want to make out with?",
  "What’s your biggest sexual fear?",
  "if your p***y was the key to my success will you give it to me",
  "How do you really feel about sex?",
  "How would you feel if my dick was on your pussy right now?",
  "Do you think my pussy will be sweeter than honey",
  "Do you think my dick wil be sweeter than honey",
  "Hw will u feel if my p***y was on your dick right now?",
  "Do u prefer skin to skin or condom?",
  "Do you like being lick on your pussy while sex is going on",
  "If u were to choose a sex time for both of us, how long will that be?",
  "Do I make u nervous",
  "What is your position on premarital sex?",
  "Tell me one thing I could do that would make you immediately orgasm.",
  "What is your favorite body part for me to suck on?",
  "Would you prefer to dominate me in bed or do you want me to dominate you in bed?",
  "Which is your favorite kind of sex: soft, slow, and sweet or aggressive, fast, and feisty?",
  "If we could only have sex in one position for a month, what position would you pick pussy or ass",
  "Is there something you've seen in a steamy movie that you'd like to try?",
  "What do you think is the sexiest part of your body is?",
  "Would you consider yourself flexible (in bed)?",
  "Why did you break up with your last boyfriend or girlfriend?",
  "What position have you always wanted to try?",
  "What do you wish we did in the bedroom?",
  "Where do you love to have sex?",
  "If you could have sex in any location in the world, where would it be?",
  "Where, and how, can I touch you that will turn you on?",
  "Hw will u like to be sex on your first sex",
  "If I was with you, which part of my body would you want to lick first?",
  "If I was with you right now, what would you do with me?",
  "If u were asked to give me a sex position, were will that be p***y or ass?",
  "Name three things you will like to do during sex.",
  "Hw many times a week would you want to have sex?",
  "Do you think it’s possible to have a friend with benefits?",
  "If I allowed you to do anything to me what would you do?",
  "How much do you like dirty talk?",
  "How will you take it if I put my hand underneath your shirt right now?",
  "What color of underwear do you think I am wearing right now?",
  "How likely will you allow me to touch you down there?",
  "Have you ever wanted to tear my clothes off?",
  "Which position is your favorite for us?",
  "If you could choose anything on my body to see right now what would it be?",
  "What is the difference to you between sex and making love?",
  "What’s your secret move to turn a guy on?",
  "What should a guy do to make you wet?",
  "Did you ever felt hot in shower while rubbing your body?",
  "Do you like your boobs being pressed?",
  "Can you tell me some reasons why I like you?",
  "Do you miss me right now?",
  "Is there anything you’re too nervous to tell me in person?",
  "Do you want to see me without my shirt on?",
  "Wat part of your body will you let me touch?",
  "Would u like to be kissed while having sex?",
  "Name the sex position you would like us to try?",
  "Hw many sex position do you know?",
  "Are you a jealous person",
  "Have someone ever make an attempt to have sex with you?",
  "Would you like me to be the person that will disvirgins you?",
  "How would you feel if someone sends u pron?",
  "At wat age do u plan to get married?",
  "How long can u last in bed?",
  "Do u discuss your relationship with your friends?",
  "Wat do u feel like when sex is on your mind?",
  "Do you think we’d do something funny if we get drunk together?",
  "Do you think you’re a good kisser?",
  "Where on your body would you like me to massage?",
  "What would you do if I come to you naked?",
  "What would you ask me to do for you if I were naked right now?",
  "Can you take my panties off with just your teeth?",
  "How would you start with me if I was in your bed right now?",
  "What would you do if we were home alone naked together?",
  "What would you like to hear from me while we do it?",
  "If you could only feel me in one place, where would it be?",
  "If you are still a virgin, how would you demand it?",
  "Have you ever been seduced by someone?",
  "Would you ever want to play dirty with me?",
  "Do u like me being ontop u or u being ontop me?",
  "Do you like it when I pull your hair during sex?",
  "Are u a dick sucker",
  "How can I make sex more enjoyable for you?",
  "Does knowing that people can hear us having sex turn you on?",
  "Do you consider yourself a naughty girl? If yes, prove it.",
  "What is the one thing you can never resist and that instantly gets you wet?",
  "Would you have sex with me while somebody is watching us?",
  "Would you make out with another girl while I watch?",
  "Would you like it if I sent you naked pictures of me?",
  "Are you confident about showing your naked body?",
  "Have you ever been hot for a teacher?",
  "are you a shy guy, sexually?",
  "Would you prefer my dick deep inside your pussy or at the bottom?",
  "What part of my body would you want me to tattoo?",
  "have you ever stared at my butt or chest?",
  "Is laughing in sex okay, or it has to be serious?",
  "Have you ever tried edible underwear?",
  "Do you like experimenting with different positions, or your favorite?",
  "If you could choose anything on my body to see right now what would it be?",
  "Which part of guys body you want to touch or feel?",
  "Have you ever kissed a girl?",
  "How many minutes should my d**k or p***y should stay inside yours without removing it?",
  "Wanna fuck my ass or pussy?",
  "Do you prefer to take the lead for sex?",
  "What do you think is the sexiest thing about my body?",
  "How do you like to be touched by me?",
  "How would you start with me if I was in your bed right now?",
  "Can I watch you play with your stuff",
  "Do u have a condom?",
  "Figure out how my pussy will looks like",
  "Figure out how my dick wii looks like",
  "If I was home alone and I ask for sex will u let me placed my dick on your pussy?",
  "If sex was wat I asked as a birthday gift will u give it to me?",
  "Do u think your mom was a virgin when your dad met her?",
  "If we were to have sex will u let any one knows about it?",
  "Do u prefer being sucked on your pussy before sex?",
  "Do u prefer being sucked on your dick before sex?",
  "What do you want sex, romance,wet kiss?",
  "What should I say if I wanted sex from u?",
  "Wat would you say if I said I wanted sex?",
  "if we were both shy for sex mood, hw Would u make mi interested,?",
  "Who was your first girlfriend",
  "What turns you on most during sex?",
  "How many times have you been in love?",
  "Who are your ex-girlfriends, (if any) and what made the relationship end as it did?",
  "Have you ever lied to me?",
  "Will u be surprised if I ask u for sex?",
  "Last time you had a wet dream?",
  "How will it feel like to lose your virginity?",
  "Would you ever watch porn with a girl?",
  "What would you do if I put my hands under your shirt?",
  "If you are still a virgin, what do you want your first time to be like?",
  "Do you like to be loud during s..x?",
  "Do you like it when I don’t wear any underwear?",
  "Do you want to cuddle with me?",
  "What is your favorite position when you are on top?",
  "Would you ever want to be blindfolded during sex?",
  "What is the quickest that you think you can undress me?",
  "Do you think you can get naked in less than 5 seconds during sex?",
  "Do you like to do it with clothes on or off?",
  "Do you want to spank me?",
  "Your lips look lonely. Do you want my lips to keep them company?",
  "Do you think that I can handle you?",
  "Do you like being naked or are you shy about it?",
  "If you realized that someone was watching you have s..x, would you stop or would you keep going?",
  "Is there anything that you would not do in bed?",
  "How long will it take you to get over here and into my pants?",
  "What is the sexiest outfit that you can think of?",
  "Does talking dirty turn you on, and do you want to try it with me?",
  "Are you into phone sex, and do you want to try it?",
  "What is the thing that makes you feel good the most during sex?",
  "Do you like foreplay or do you like going straight to business?",
  "Do you like it when I come inside you?",
  "Do you like to watch me as I change clothes?",
  "Do you like it when I touch you slowly all over your body?",
  "Which part of me do you miss the most right now?",
  "If we only had 20 minutes together, what would we do?",
  "Does thinking about me make you wet?",
  "How long should foreplay take before sex?",
  "Describe to me in detail what it feels like when I’m inside you.",
  "Do you like it when I tell you what to do?",
  "What is a sure way to turn you on within seconds?",
  "Do you prefer younger or older men?",
  "Are you enjoying these flirty questions?",
  "When was the last time you jerked off thinking of me?",
  "Do you like it when I make the first move?",
  "Do you have a name for your thing and what is it?",
  "Do you get an instant erection when you see someone naked?",
  "If you had to choose between getting head or having sex, which would you pick?",
  "Do you think I’m sexy?",
  "What is your favorite thing to do with my body?",
  "Do you like it when people can hear us having sex?",
  "When are u coming to sex me?",
  "When am I coming to make u feed good?",
  "If u were shy to ask for the sex while we are inside, will u tell me through your phone?",
  "Do u like condom to be fixed in your presence or your obsence?",
  "Do you think my dick will enter your pussy?",
  "If your p***y was so tight for my d**k, wat will u do when u are in the mood?",
  "If you were crying while I was penetrating should I stop?",
  "If my dick was on your pussy, were should I put my hands when sex is going on?",
  "Which do you prefer, eyes opend, or eyes closed while having sex?",
  "Will u Send me a photo of how my dick should be inside your p***y",
  "Will u Send me a photo of how my p***y should be inside your d**k",
  "When was a time you were so turned on you couldn’t stand it?",
  "Do you ever just want to tear off my clothes?",
  "Would you prefer to see me in hot pants or a short skirt?",
  "Will u like it if I fuck you for 2 minutes?",
  "How do you like your breasts and nipples played with?",
  "When did you first learn about sex?",
  "How much eye contact do you like to have during sex?",
  "What's the sexiest movie you've ever watched?",
  "What’s your favorite pair or underwear?",
  "Using three words, how do you feel about me?",
  "How do you want me?",
  "Would you like to know how I feel about you?",
  "Where would you like to have sex My place or yours?",
  "If I was at your window right now, would you invite me in?",
  "If you could kiss me goodnight every night, would you?",
  "Would you like the cap of my dick being robbed on your pussy before entering?",
  "Would you be loud or quiet during sex?",
  "Do you prefer to take control or be submissive?",
  "What would you like me to do more in bed?",
  "Is your ass soft ?",
  "What is your favorite kind of kiss?",
  "Do you like when I take you in deep or when you take me in deep?",
  "Will you like it when I touch you there?",
  "Have u ever felt horny while texting on the phone?",
  "Who was the first girl that touch your dick?",
  "who was the first boy that touch your ass?",
  "Which girl do u think would give you the best sex?",
  "Should u prefer we watch pron before sex?",
  "Which boy do u think would give you the best sex?",
  "Who do u fantasize when u think about sex?",
  "Have you ever gone a whole day without wearing underwear?",
  "What would you do if I answered the door naked?",
  "If I was sexing u and my dick drove out from your pussy, will u put it back ur self, or should I be the one to put it back my self?",
  "Will u be mad if I already made u wet by robbing my dick ontop your pussy and didn't do any tin?",
  "Will u like your breast to be sucked while fucking?"
];